import bcrypt from 'bcryptjs'
const data = {
	users: [
		{
			name: 'Howard',
			email: 'admin@example.com',
			password: bcrypt.hashSync('1234', 8),
			isAdmin: true,
			type: 'normal',
		},
		{
			name: 'Nicolas',
			email: 'user@example.com',
			password: bcrypt.hashSync('1234', 8),
			isAdmin: false,
			type: 'normal',
		},
	],
	products: [
		{
			name: 'Heart Ring',
			category: 'Ring',
			image: '/images/p1.jpg',
			price: 5,
			wsPrice: 2.5,
			wzPrice: 2,
			countInStock: 100,
			rating: 4.5,
			numReviews: 10,
			description: 'high quality product',
		},
		{
			name: 'Circle Ring',
			category: 'Ring',
			image: '/images/p2.jpg',
			price: 5,
			wsPrice: 2.5,
			wzPrice: 2,
			countInStock: 100,
			rating: 4.5,
			numReviews: 10,
			description: 'high quality product',
		},
		{
			name: 'Crystal Ring',
			category: 'Ring',
			image: '/images/p3.jpg',
			price: 5,
			wsPrice: 2.5,
			wzPrice: 2,
			countInStock: 100,
			rating: 4.5,
			numReviews: 10,
			description: 'high quality product',
		},
		{
			name: 'Gold Filled Tennis Chain',
			category: 'Necklace',
			image: '/images/p4.jpg',
			price: 10,
			wsPrice: 6,
			wzPrice: 6,
			countInStock: 100,
			rating: 4.5,
			numReviews: 10,
			description: 'high quality product',
		},
		{
			name: 'Gold Filled Tennis chain',
			category: 'Necklace',
			image: '/images/p5.jpg',
			price: 5,
			wsPrice: 2.5,
			wzPrice: 2,
			countInStock: 100,
			rating: 4.5,
			numReviews: 10,
			description: 'high quality product',
		},
		{
			name: 'Eye anklet',
			category: 'Anklet',
			image: '/images/p6.jpg',
			price: 5,
			wsPrice: 2.5,
			wzPrice: 2,
			countInStock: 100,
			rating: 4.5,
			numReviews: 10,
			description: 'high quality product',
		},
		{
			name: 'Eye bracelet',
			category: 'Bracelet',
			image: '/images/p7.jpg',
			price: 5,
			wsPrice: 2.5,
			wzPrice: 2,
			countInStock: 100,
			rating: 4.5,
			numReviews: 10,
			description: 'high quality product',
		},
		{
			name: 'Eye chain',
			category: 'Necklace',
			image: '/images/p8.jpg',
			price: 10,
			wsPrice: 4,
			wzPrice: 4,
			countInStock: 100,
			rating: 4.5,
			numReviews: 10,
			description: 'high quality product',
		},
	],
}

export default data
